Repository TEAMShiftM/ShiftM-SERVER, pull requests merged in 2025-03, with the labels that each got.

#19 feat(#14): 회사 정보 CRU API 구현
  src/main/java/com/shiftm/shiftm/domain/company/api/AdminCompanyController.java
  src/main/java/com/shiftm/shiftm/domain/company/api/CompanyController.java
  src/main/java/com/shiftm/shiftm/domain/company/domain/Company.java
  src/main/java/com/shiftm/shiftm/domain/company/dto/request/CompanyReqDto.java
  src/main/java/com/shiftm/shiftm/domain/company/dto/request/CompanyRequest.java
  src/main/java/com/shiftm/shiftm/domain/company/dto/response/CompanyResDto.java
  src/main/java/com/shiftm/shiftm/domain/company/dto/response/CompanyResponse.java
  src/main/java/com/shiftm/shiftm/domain/company/exception/CompanyAlreadyExistsException.java
  src/main/java/com/shiftm/shiftm/domain/company/exception/CompanyException.java
  src/main/java/com/shiftm/shiftm/domain/company/exception/CompanyNotFoundException.java
  src/main/java/com/shiftm/shiftm/domain/company/repository/CompanyRepository.java
  src/main/java/com/shiftm/shiftm/domain/company/service/CompanyService.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
  src/test/java/com/shiftm/shiftm/domain/company/domain/CompanyBuilder.java
  src/test/java/com/shiftm/shiftm/domain/company/dto/CompanyRequestBuilder.java
  src/test/java/com/shiftm/shiftm/domain/company/service/CompanyServiceTest.java
Labels: ✨ Feature

#26 feat(#25): 회원 가입 관련 API 구현
  build.gradle
  src/main/java/com/shiftm/shiftm/domain/member/api/MemberController.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/request/VerifyEmailCodeRequest.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/response/CheckResponse.java
  src/main/java/com/shiftm/shiftm/domain/member/service/MemberService.java
  src/main/java/com/shiftm/shiftm/global/config/EmailConfig.java
  src/main/java/com/shiftm/shiftm/global/config/SecurityConfig.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
  src/main/java/com/shiftm/shiftm/infra/email/MailSender.java
  src/main/java/com/shiftm/shiftm/infra/email/exception/UnableToSendEmailException.java
Labels: ✨ Feature

#28 feat(#15): 사용자용 근무 기록 API 구현
  src/main/java/com/shiftm/shiftm/domain/shift/api/ShiftController.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/Checkin.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/Checkout.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/Shift.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/enums/Status.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/request/AfterCheckinRequest.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/request/CheckinRequest.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/request/CheckoutRequest.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/request/ShiftReqDto.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/AfterCheckinResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/CheckinResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/CheckoutResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/ShiftListResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/ShiftResDto.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/ShiftResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/exception/CheckinAlreadyExistsException.java
  src/main/java/com/shiftm/shiftm/domain/shift/exception/ShiftException.java
  src/main/java/com/shiftm/shiftm/domain/shift/exception/ShiftNotFoundException.java
  src/main/java/com/shiftm/shiftm/domain/shift/repository/ShiftRepository.java
  src/main/java/com/shiftm/shiftm/domain/shift/service/ShiftService.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
  src/test/java/com/shiftm/shiftm/domain/shift/service/ShiftServiceTest.java
Labels: ✨ Feature

#30 feat(#27): 회원 정보 수정, 삭제 API 구현
  src/main/java/com/shiftm/shiftm/domain/member/api/MemberController.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/Member.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/request/UpdatePasswordRequest.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/request/UpdateRequest.java
  src/main/java/com/shiftm/shiftm/domain/member/exception/PasswordNotMatchException.java
  src/main/java/com/shiftm/shiftm/domain/member/service/MemberService.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
Labels: ✨ Feature

#34 feat(#31): 아이디, 비밀번호 찾기 API 구현
  src/main/java/com/shiftm/shiftm/domain/member/api/MemberController.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/request/FindIdRequest.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/request/FindPasswordRequest.java
  src/main/java/com/shiftm/shiftm/domain/member/repository/MemberDao.java
  src/main/java/com/shiftm/shiftm/domain/member/repository/MemberRepository.java
  src/main/java/com/shiftm/shiftm/domain/member/service/MemberService.java
  src/main/java/com/shiftm/shiftm/global/config/SecurityConfig.java
Labels: ✨ Feature

#36 feat(#17): 연차 신청 및 현황 조회 API 구현, 연차 신청 상태 변경 API 구현
  src/main/java/com/shiftm/shiftm/domain/leave/api/AdminLeaveController.java
  src/main/java/com/shiftm/shiftm/domain/leave/api/LeaveController.java
  src/main/java/com/shiftm/shiftm/domain/leave/api/LeaveTypeController.java
  src/main/java/com/shiftm/shiftm/domain/leave/domain/Leave.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/LeaveListResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/LeaveResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/repository/LeaveRepository.java
  src/main/java/com/shiftm/shiftm/domain/leave/service/LeaveService.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/api/AdminLeaveRequestController.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/api/LeaveRequestController.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/dto/response/LeaveRequestListResponse.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/dto/response/LeaveRequestResponse.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/exception/LeaveRequestNotFoundException.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/repository/LeaveRequestRepository.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/service/LeaveRequestService.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
Labels: ✨ Feature

#37 feat(#35): 관리자 - 회원 관련 API 구현
  src/main/java/com/shiftm/shiftm/domain/member/api/AdminMemberController.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/Member.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/request/UpdateForAdminRequest.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/response/MemberResponse.java
  src/main/java/com/shiftm/shiftm/domain/member/repository/MemberRepository.java
  src/main/java/com/shiftm/shiftm/domain/member/service/MemberService.java
Labels: ✨ Feature

#42 feat(#41): BaseEntity 생성
  src/main/java/com/shiftm/shiftm/domain/company/domain/Company.java
  src/main/java/com/shiftm/shiftm/domain/leave/domain/Leave.java
  src/main/java/com/shiftm/shiftm/domain/leave/domain/LeaveType.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/domain/LeaveRequest.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/Member.java
  src/main/java/com/shiftm/shiftm/domain/objection/domain/Objection.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/Shift.java
  src/main/java/com/shiftm/shiftm/global/common/domain/BaseEntity.java
  src/main/java/com/shiftm/shiftm/global/config/JpaAuditingConfig.java
Labels: ✨ Feature

#45 setting(#44): QueryDsl 환경 설정
  .gitignore
  build.gradle
  src/main/java/com/shiftm/shiftm/global/config/QueryDslConfig.java
Labels: ⚙️ Setting

#48 bug(#47): Swagger 및 테스트 코드 에러 수정
  src/main/java/com/shiftm/shiftm/global/auth/annotation/AuthId.java
  src/test/java/com/shiftm/shiftm/domain/leave/service/LeaveTypeServiceTest.java
Labels: 🐛 Bug

#50 refactor(#49) Member API 리팩토링
  src/main/java/com/shiftm/shiftm/domain/auth/service/AuthService.java
  src/main/java/com/shiftm/shiftm/domain/leave/service/LeaveService.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/service/LeaveRequestService.java
  src/main/java/com/shiftm/shiftm/domain/member/api/AdminMemberController.java
  src/main/java/com/shiftm/shiftm/domain/member/api/MemberController.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/Member.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/response/ListMemberResponse.java
  src/main/java/com/shiftm/shiftm/domain/member/exception/DuplicatedEmailException.java
  src/main/java/com/shiftm/shiftm/domain/member/exception/DuplicatedIdException.java
  src/main/java/com/shiftm/shiftm/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/shiftm/shiftm/domain/member/exception/PasswordNotMatchException.java
  src/main/java/com/shiftm/shiftm/domain/member/repository/MemberFindDao.java
  src/main/java/com/shiftm/shiftm/domain/member/repository/MemberRepository.java
  src/main/java/com/shiftm/shiftm/domain/member/service/MemberService.java
  src/main/java/com/shiftm/shiftm/domain/shift/service/ShiftService.java
  src/main/java/com/shiftm/shiftm/global/auth/filter/JwtAuthFilter.java
  src/test/java/com/shiftm/shiftm/domain/auth/service/AuthServiceTest.java
  src/test/java/com/shiftm/shiftm/domain/auth/service/ReissueTest.java
  src/test/java/com/shiftm/shiftm/domain/member/service/MemberServiceTest.java
  src/test/java/com/shiftm/shiftm/domain/shift/service/ShiftServiceTest.java
Labels: 🛠️ Refactor

#53 deploy(#52): JIB 플러그인 추가
  build.gradle
Labels: 🌏 Deploy

#54 refactor(#51) 출근 신청 API와 사후 출근 신청 API 통합
  src/main/java/com/shiftm/shiftm/domain/company/api/CompanyController.java
  src/main/java/com/shiftm/shiftm/domain/company/repository/CompanyFindDao.java
  src/main/java/com/shiftm/shiftm/domain/company/service/CompanyService.java
  src/main/java/com/shiftm/shiftm/domain/shift/api/AdminShiftController.java
  src/main/java/com/shiftm/shiftm/domain/shift/api/ShiftController.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/Checkin.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/Shift.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/request/CheckinRequest.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/AdminAfterCheckinResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/AdminShiftListResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/AfterCheckinListResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/CheckinResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/ListAdminShiftResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/dto/response/ListAfterCheckinResponse.java
  src/main/java/com/shiftm/shiftm/domain/shift/service/ShiftService.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
  src/main/java/com/shiftm/shiftm/global/util/.gitkeep
  src/main/java/com/shiftm/shiftm/global/util/DistanceUtil.java
  src/main/java/com/shiftm/shiftm/infra/geocoding/GeocodingResponse.java
  src/main/java/com/shiftm/shiftm/infra/geocoding/KakaoGeocodingClient.java
  src/main/java/com/shiftm/shiftm/infra/geocoding/exception/AdressNotFoundException.java
  src/main/java/com/shiftm/shiftm/infra/geocoding/exception/GeocodingException.java
  src/test/java/com/shiftm/shiftm/domain/shift/service/ShiftServiceTest.java
Labels: ✨ Feature, 🛠️ Refactor

#63 feat(#60): 연차 관련 비즈니스 로직 수정
  src/main/java/com/shiftm/shiftm/domain/leave/api/AdminLeaveController.java
  src/main/java/com/shiftm/shiftm/domain/leave/api/LeaveController.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/request/CreateLeaveRequest.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/AdminLeaveResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/LeaveCountResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/LeaveListResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/LeaveResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/ListAdminLeaveCreateResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/ListAdminLeaveResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/ListLeaveResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/repository/CustomLeaveRepository.java
  src/main/java/com/shiftm/shiftm/domain/leave/repository/LeaveFindDao.java
  src/main/java/com/shiftm/shiftm/domain/leave/repository/LeaveRepository.java
  src/main/java/com/shiftm/shiftm/domain/leave/service/LeaveService.java
  src/main/java/com/shiftm/shiftm/domain/member/repository/MemberFindDao.java
  src/test/java/com/shiftm/shiftm/domain/leave/domain/LeaveBuilder.java
  src/test/java/com/shiftm/shiftm/domain/leave/dto/CreateLeaveRequestBuilder.java
  src/test/java/com/shiftm/shiftm/domain/leave/dto/UpdateLeaveRequestBuilder.java
  src/test/java/com/shiftm/shiftm/domain/leave/service/LeaveServiceTest.java
Labels: ✨ Feature
