Repository TEAMShiftM/ShiftM-SERVER, pull requests merged in 2025-02, with the labels that each got.

#5 feat(#3): Entity 구현
  .gitignore
  src/main/java/com/shiftm/shiftm/domain/company/domain/Company.java
  src/main/java/com/shiftm/shiftm/domain/leave/domain/Leave.java
  src/main/java/com/shiftm/shiftm/domain/leave/domain/LeaveType.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/domain/LeaveRequest.java
  src/main/java/com/shiftm/shiftm/domain/leaverequest/domain/enums/Status.java
  src/main/java/com/shiftm/shiftm/domain/leavetype/api/LeaveTypeController.java
  src/main/java/com/shiftm/shiftm/domain/leavetype/domain/LeaveType.java
  src/main/java/com/shiftm/shiftm/domain/leavetype/dto/request/LeaveTypeReqDto.java
  src/main/java/com/shiftm/shiftm/domain/leavetype/dto/response/LeaveTypeResDto.java
  src/main/java/com/shiftm/shiftm/domain/leavetype/exception/LeaveTypeException.java
  src/main/java/com/shiftm/shiftm/domain/leavetype/repository/LeaveTypeRepository.java
  src/main/java/com/shiftm/shiftm/domain/leavetype/service/LeaveTypeService.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/Member.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/enums/Gender.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/enums/Role.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/enums/Status.java
  src/main/java/com/shiftm/shiftm/domain/objection/domain/Objection.java
  src/main/java/com/shiftm/shiftm/domain/objection/domain/enums/Status.java
  src/main/java/com/shiftm/shiftm/domain/objection/domain/enums/Type.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/Checkin.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/Checkout.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/Shift.java
  src/main/java/com/shiftm/shiftm/domain/shift/domain/enums/Status.java
Labels: ✨ Feature

#8 feat(#7): Common ErrorHandler 구현
  src/main/java/com/shiftm/shiftm/global/error/.gitkeep
  src/main/java/com/shiftm/shiftm/global/error/BusinessException.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorResponse.java
  src/main/java/com/shiftm/shiftm/global/error/GlobalExceptionHandler.java
Labels: ✨ Feature

#11 feat(#9): 회원 가입 API 구현
  build.gradle
  src/main/java/com/shiftm/shiftm/domain/member/api/MemberController.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/Member.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/request/MemberReqDto.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/request/SignUpRequest.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/response/MemberResDto.java
  src/main/java/com/shiftm/shiftm/domain/member/dto/response/MemberResponse.java
  src/main/java/com/shiftm/shiftm/domain/member/exception/DuplicatedEmailException.java
  src/main/java/com/shiftm/shiftm/domain/member/exception/DuplicatedIdException.java
  src/main/java/com/shiftm/shiftm/domain/member/exception/MemberException.java
  src/main/java/com/shiftm/shiftm/domain/member/repository/MemberRepository.java
  src/main/java/com/shiftm/shiftm/domain/member/service/MemberService.java
  src/main/java/com/shiftm/shiftm/global/config/.gitkeep
  src/main/java/com/shiftm/shiftm/global/config/SecurityConfig.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
  src/main/java/com/shiftm/shiftm/global/error/GlobalExceptionHandler.java
  src/main/java/com/shiftm/shiftm/global/error/exception/BusinessException.java
  src/main/java/com/shiftm/shiftm/global/error/exception/InvalidValueException.java
  src/main/resources/application.properties
  src/test/java/com/shiftm/shiftm/domain/member/domain/MemberBuilder.java
  src/test/java/com/shiftm/shiftm/domain/member/dto/SignUpRequestBuilder.java
  src/test/java/com/shiftm/shiftm/domain/member/service/MemberServiceTest.java
  src/test/java/com/shiftm/shiftm/test/UnitTest.java
Labels: ✨ Feature

#13 feat(#10): 연차 유형 CRU API 구현
  .DS_Store
  src/main/java/com/shiftm/shiftm/domain/leave/api/AdminLeaveTypeController.java
  src/main/java/com/shiftm/shiftm/domain/leave/api/LeaveTypeController.java
  src/main/java/com/shiftm/shiftm/domain/leave/domain/LeaveType.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/request/LeaveTypeRequest.java
  src/main/java/com/shiftm/shiftm/domain/leave/dto/response/LeaveTypeResponse.java
  src/main/java/com/shiftm/shiftm/domain/leave/exception/DuplicatedNameException.java
  src/main/java/com/shiftm/shiftm/domain/leave/exception/NotFoundLeaveTypeException.java
  src/main/java/com/shiftm/shiftm/domain/leave/repository/LeaveTypeRepository.java
  src/main/java/com/shiftm/shiftm/domain/leave/service/LeaveTypeService.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
  src/test/java/com/shiftm/shiftm/domain/leave/service/LeaveTypeServiceTest.java
Labels: ✨ Feature

#16 feat(#12): 로그인 관련 API 구현
  build.gradle
  src/main/java/com/shiftm/shiftm/domain/auth/api/AuthController.java
  src/main/java/com/shiftm/shiftm/domain/auth/dto/request/LoginRequest.java
  src/main/java/com/shiftm/shiftm/domain/auth/dto/response/TokenResponse.java
  src/main/java/com/shiftm/shiftm/domain/auth/exception/InvalidBearerPrefixException.java
  src/main/java/com/shiftm/shiftm/domain/auth/exception/InvalidPasswordException.java
  src/main/java/com/shiftm/shiftm/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/shiftm/shiftm/domain/auth/service/AuthService.java
  src/main/java/com/shiftm/shiftm/domain/member/domain/enums/Role.java
  src/main/java/com/shiftm/shiftm/domain/member/exception/MemberNotFoundException.java
  src/main/java/com/shiftm/shiftm/domain/member/repository/MemberDao.java
  src/main/java/com/shiftm/shiftm/domain/member/service/MemberService.java
  src/main/java/com/shiftm/shiftm/global/auth/annotation/AuthId.java
  src/main/java/com/shiftm/shiftm/global/auth/annotation/AuthIdResolver.java
  src/main/java/com/shiftm/shiftm/global/auth/filter/JwtAuthFilter.java
  src/main/java/com/shiftm/shiftm/global/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/com/shiftm/shiftm/global/auth/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/shiftm/shiftm/global/auth/jwt/JwtGenerator.java
  src/main/java/com/shiftm/shiftm/global/auth/jwt/JwtValidator.java
  src/main/java/com/shiftm/shiftm/global/config/RedisConfig.java
  src/main/java/com/shiftm/shiftm/global/config/SecurityConfig.java
  src/main/java/com/shiftm/shiftm/global/config/WebConfigurer.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
  src/main/java/com/shiftm/shiftm/global/error/exception/EntityNotFoundException.java
  src/main/java/com/shiftm/shiftm/infra/redis/RedisService.java
  src/test/java/com/shiftm/shiftm/domain/auth/dto/LoginRequestBuilder.java
  src/test/java/com/shiftm/shiftm/domain/auth/service/AuthServiceTest.java
  src/test/java/com/shiftm/shiftm/domain/auth/service/ReissueTest.java
  src/test/java/com/shiftm/shiftm/domain/member/domain/MemberBuilder.java
  src/test/java/com/shiftm/shiftm/domain/member/service/MemberServiceTest.java
Labels: ✨ Feature

#21 bug(#20): 로그인 버그 수정
  src/main/java/com/shiftm/shiftm/global/auth/filter/JwtAuthFilter.java
  src/main/java/com/shiftm/shiftm/global/config/RedisConfig.java
  src/main/java/com/shiftm/shiftm/global/error/ErrorCode.java
Labels: 🐛 Bug

#23 setting(#22): Swagger 환경 설정
  src/main/java/com/shiftm/shiftm/global/config/SwaggerConfig.java
Labels: ⚙️ Setting

#24 feat(#18): 회원 정보 조회 API 구현
  src/main/java/com/shiftm/shiftm/domain/member/api/MemberController.java
  src/main/java/com/shiftm/shiftm/domain/member/service/MemberService.java
  src/test/java/com/shiftm/shiftm/domain/member/service/MemberServiceTest.java
Labels: ✨ Feature
